[project]
name = "kubernetes-workshop"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-aws>=6.0.2,<7.0.0",
    "pulumi-awsx>=2.21.1",
    "pulumi-eks>=3.8.1",
    "pulumi-kubernetes>=4.22.1",
]
